# Generated by Django 4.2.2 on 2023-06-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GardenEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter username', max_length=20)),
                ('UserEntryNum', models.CharField(help_text='Enter username and entry number (ex. P1Ent1 for user P1 first entry)', max_length=20)),
                ('picture', models.ImageField(blank=True, help_text='Upload an update picture of your plant', null=True, upload_to='images/')),
                ('sound', models.FileField(blank=True, help_text='Upload a sound file', null=True, upload_to='sounds/')),
                ('rating', models.IntegerField(help_text='Enter the rating (out of 5)')),
                ('message', models.TextField(help_text='Enter the message', max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
