# Generated by Django 4.2.2 on 2023-06-21 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livingsound', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardenentry',
            name='UserEntryNum',
        ),
        migrations.AlterField(
            model_name='gardenentry',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
