# Generated by Django 4.2.2 on 2023-06-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livingsound', '0005_alter_gardenentry_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenentry',
            name='picture',
            field=models.ImageField(help_text='Upload an update picture of your plant', upload_to='images/'),
        ),
    ]
