# Generated by Django 4.2.2 on 2023-06-28 23:05

from django.db import migrations, models
import livingsound.models


class Migration(migrations.Migration):

    dependencies = [
        ('livingsound', '0006_alter_gardenentry_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenentry',
            name='picture',
            field=models.ImageField(blank=True, help_text='Upload an update picture of your plant', null=True, upload_to=livingsound.models.GardenEntry.user_directory_path_img),
        ),
        migrations.AlterField(
            model_name='gardenentry',
            name='sound',
            field=models.FileField(blank=True, help_text='Upload a sound file', null=True, upload_to=livingsound.models.GardenEntry.user_directory_path_sound),
        ),
    ]
