# Generated by Django 4.2.2 on 2023-07-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livingsound', '0007_alter_gardenentry_picture_alter_gardenentry_sound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardenentry',
            name='sound',
        ),
    ]
