# Generated by Django 4.2.2 on 2023-07-03 15:31

from django.db import migrations, models
import livingsound.models


class Migration(migrations.Migration):

    dependencies = [
        ('livingsound', '0008_remove_gardenentry_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenentry',
            name='sound',
            field=models.FileField(blank=True, help_text='Upload a sound file', null=True, upload_to=livingsound.models.GardenEntry.user_directory_path_sound),
        ),
    ]
