# Generated by Django 4.2.2 on 2023-07-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livingsound', '0010_sound'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sound',
        ),
    ]
