runtime: python311 # or another supported version

entrypoint: gunicorn -b :$PORT web_project.wsgi

env_variables:
  APPENGINE_URL: https://PROJECT_ID.REGION_ID.r.appspot.com

handlers:
- url: /static
  static_dir: livingsound/static/

- url: /.*
  secure: always
  script: auto