runtime: python39 # or another supported version

entrypoint: gunicorn -b :$PORT livingsound.wsgi

env_variables:
  APPENGINE_URL: https://livingsound.uc.r.appspot.com

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /static
  static_dir: static/

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto